Mr outman lacheheb---#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

void *entry_point(void *value) {
    printf("hello from the second thread :)\n");

    int *num = (int *) value;

    printf("the value of value is %d", *num);

    return NULL;
}

int main(int argc, char **argv) {
    pthread_t thread;

    printf("hello from the first thread :D\n");

    int num = 123;

    pthread_create(&thread, NULL, entry_point, &num);

    pthread_join(thread, NULL);

    return EXIT_SUCCESS;
}

name: Status Update
about: A brief status update.
body:
  - type: dropdown
    attributes:
      name: Status
      options:
        - name: "GREEN \U0001F34F (All good, smooth sailing)"
          value: 'Status: GREEN'
        - name: "YELLOW \U0001F7E1 (On track, with hurdles to work through)"
          value: 'Status: YELLOW'
        - name: "RED \U0001F534 (BLOCKED)"
          value: 'Status: RED'
  - type: input
    attributes:
      name: Update Summary
      placeholder:
        Brief summary of the status and next steps. Any blockers should be
        called out specifically.
      inputType: longText
  - type: input
    attributes:
      name: 'Attribution'
      value: '_created with :heart: by typing_ `/status`'
      inputType: text
